enhance(image-picker):增加组件上传状态功能以及demo展示
b2nil/taro-ui-vue3 pull request #86
Opened 2021-03-10 03:53 UTC by unforesndprson

enhance(image-picker):增加组件上传状态功能以及demo展示

2021-03-10 07:20 UTC, b2nil commented
感谢 PR！

关于定义文件里面的 version `@since v2.0.2`，目前版本号来自 `Taro UI` 以前的 legacy code。
现在要在写从哪个版本开始支持 PR 所涉及的功能时， 请写 `taro-ui-vue3` 最新的版本，目前是 `1.0.0-alpha18`。


关于这个 PR，新增的两个字段，`status` 和 `message` 具体是如何更新的？需要在 `Taro.chooseImage` 的 `onSuccess` 和 `onFail` 回调函数里面来更新吗？

2021-03-10 08:08 UTC, unforesndprson commented
> 感谢 PR！
> 
> 关于定义文件里面的 version `@since v2.0.2`，目前版本号来自 `Taro UI` 以前的 legacy code。
> 现在要在写从哪个版本开始支持 PR 所涉及的功能时， 请写 `taro-ui-vue3` 最新的版本，目前是 `1.0.0-alpha18`。
> 
> 关于这个 PR，新增的两个字段，`status` 和 `message` 具体是如何更新的？需要在 `Taro.chooseImage` 的 `onSuccess` 和 `onFail` 回调函数里面来更新吗？

开发者增加图片上传时，可更新 files中status和message展示对应上传状态，和chooseImage的状态无关。

2021-03-10 10:05 UTC, b2nil commented
所以要上传图片才能看到相应的效果吗？
可否增加新增功能的 test cases？
另外可否新增可以看到 loading / failed 状态的 demo ？
现在这个 demo 我跑了一下，好像没法辨别状态。

2021-03-10 13:55 UTC, unforesndprson commented
@b2nil  最新dev分支执行yarn dev:weapp 会报错

2021-03-10 14:15 UTC, b2nil commented
报什么错误?

2021-03-11 01:33 UTC, unforesndprson commented
Module not found: Can't resolve './img.json' in '/Users/zoney/Documents/code/github/tmp/taro-ui-vue3/lib/components/toast'

2021-03-11 02:02 UTC, b2nil commented
hi @unforesndprson 
看一下你的 local repo 是不是同步了最新的内容。
如果是的话，应该有一个 `build` 目录，里面写了采用 esbuild 快速编译开发用的库的脚本。其中有一个文件`https://github.com/b2nil/taro-ui-vue3/blob/dev/build/esbuild.build.js`，这里面有个`ToastPlugin`插件是负责把 img.json 更换为 img.js 的。

我在本地是能顺利编译的。

2021-03-11 02:06 UTC, b2nil commented
@unforesndprson 
当然也可以直接把 `package.json` 里面的 `scripts` 改为: `"dev:weapp": "taro build --type weapp --watch",` 直接跑。
但是采用这种方式，要把 `config/index.js` 中的第 24 行 `'taro-ui-vue3$': path.resolve(__dirname, '..', 'lib'),` 注释掉。

2021-03-11 02:22 UTC, unforesndprson commented
> 看一下你的 local repo 是不是同步了最新的内容。

esbuild.build.js 中的filter: /toast\\index.ts$/  改成filter: /toast\/index.ts$/  就正常了，你本地代码用filter: /toast\\index.ts$/ 可以编译？

2021-03-11 02:30 UTC, b2nil commented
Okay, 这应该是一个路径的 bug，我一直在 windows 上使用 `bash` 来编译的，没有问题。

2021-03-16 14:14 UTC, unforesndprson commented
> 所以要上传图片才能看到相应的效果吗？
> 可否增加新增功能的 test cases？
> 另外可否新增可以看到 loading / failed 状态的 demo ？
> 现在这个 demo 我跑了一下，好像没法辨别状态。

已更新，再看一下哈

2021-03-16 14:18 UTC, unforesndprson commented
另外迁移到vue3，测试案例没有更新成响应式数据。测试跑起来也有很多错误。

2021-03-18 09:02 UTC, b2nil commented
@unforesndprson 
抱歉，这周忙别的事情去了，还没跑这个 demo。
关于测试，主要是现在很多组件的测试没更新完，确实还有一些问题。
针对单个组件的测试，可修改 `jest.config.js` 里面的 `roots: ['<rootDir>/src/components']`，例如，改为: `roots: ['<rootDir>/src/components/image-picker']`，这样就只会运行 `image-picker` 组件的测试。

2021-03-21 16:10 UTC, b2nil requested changes
Please use a different color for failed status, for example, a warning red

2021-03-21 16:12 UTC, b2nil commented on src/pages/form/image-picker/index.vue
>      function onChange(stateName: string, files: DogaImage[]): void {
可否新增一个 demo：在 `onChange` 函数中通过 mock `Taro.upload` 来动态更新新增文件的上传状态

2021-03-22 05:48 UTC, unforesndprson commented on src/pages/form/image-picker/index.vue
>      function onChange(stateName: string, files: DogaImage[]): void {
@change="onChange('files4', $event)"
组件change 事件传了多个参数（files，OperationType...），像demo里需要增加自定义参数file4，$event的方式只能拿到第一个参数files。如果不修改组件change事件传的参数，有其他什么办法？

2021-03-22 06:41 UTC, b2nil commented on src/pages/form/image-picker/index.vue
>      function onChange(stateName: string, files: DogaImage[]): void {
如果需要的话，可以进行必要的更改。
或者如果通过 onChange 事件来实现不理想的话，可以参考微信拓展组件里面的 mp-uploader 组件逻辑，新增一个 upload 函数参数来控制上传的逻辑，这样可以在选择图片之后，直接调用 upload，方便控制上传状态。

2021-03-27 01:56 UTC, b2nil commented
@unforesndprson  
Hi Zoney, thanks for the patient work and sorry for the delay.
I just added two minor commits to this PR.
Please check if there is anything else you would like to add or revise.

If you are happy with all the progress now, I'll be glad to merge it today.

2021-03-27 01:56 UTC, b2nil approved these changes

2021-03-27 02:15 UTC, unforesndprson commented
@b2nil  Thanks good enough

2021-03-27 03:14 UTC, merged